language: cpp

dist: focal

compiler:
- gcc

os:
- linux

env:
- QT_VERSION=qt512 QT_PPA=qt-5.12.9
- QT_VERSION=qt514 QT_PPA=qt-5.14.2
- QT_VERSION=qt515 QT_PPA=qt-5.15.0

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-$QT_PPA-focal
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install ${QT_VERSION}base

script:
  - . /opt/$QT_VERSION/bin/$QT_VERSION-env.sh
  - qmake
  - make
  - make check

